Repository ministryofjustice/hmpps-book-secure-move-api, pull requests merged in 2020-11, with the labels that each got.

#1098 Don't create fake data that should be reference data
  README.md
  lib/tasks/fake_data.rake
Labels: WIP

#1140 P4-2248 Stop writing to person_escort_record_id in responses
  app/models/framework_question.rb
  app/models/framework_response.rb
  app/models/person_escort_record.rb
  db/migrate/20201116093301_change_person_escort_record_to_optional_on_framework_responses.rb
  db/schema.rb
  spec/factories/framework_response.rb
  spec/models/framework_question_spec.rb
  spec/models/framework_response_spec.rb
  spec/models/person_escort_record_spec.rb
  spec/serializers/framework_response_serializer_spec.rb
Labels: blocked, breaking change

#1141 P4-2248 Remove person_escort_record_id from framework responses
  app/models/framework_response.rb
  app/serializers/framework_response_serializer.rb
  db/migrate/20201116095539_remove_person_escort_record_from_framework_responses.rb
  db/schema.rb
  spec/models/framework_response_spec.rb
  spec/serializers/framework_response_serializer_spec.rb
  swagger/v1/framework_response.yaml
  swagger/v1/framework_response_include_parameter.yaml
Labels: breaking change

#1169 Remove support for including allocation on v1/v2 GET /moves and v1 GET /move
  app/controllers/api/v1/moves_actions.rb
  app/serializers/move_serializer.rb
  app/serializers/v2/moves_serializer.rb
  spec/serializers/move_serializer_spec.rb
  spec/serializers/v2/moves_serializer_spec.rb
  swagger/v1/move_include_parameter.yaml
  swagger/v2/moves_include_parameter.yaml
Labels: breaking change
